"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AlertCircle, ArrowUpRight, Banknote, CalendarDays, Clock3, FileText, History, LoaderCircle, MoreHorizontal, Plus, RefreshCw, Search, Trash2, UserRoundCheck, UsersRound, WalletCards } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { DatePicker } from "@/components/ui/date-picker";
import { useAuth } from "@/components/auth-context";
import { useLanguage } from "@/components/language-provider";
import { Field, formatDate, hrApi, HR_ROLES, HR_WRITE_ROLES, inputError, labelize, Modal, money, readableErrors, rows, Select, Textarea, today } from "@/components/hr-ui";
import { hasRole, withSectionRole } from "@/lib/roles";

const statusOptions = [["active", "Active"], ["leave", "On leave"], ["suspended", "Suspended"], ["terminated", "Terminated"]];
const configs = {
  employees: { title: "Employees", endpoint: "employees", icon: UsersRound, search: "number, name, job title, phone, or ID", columns: ["Employee", "Department", "Job title", "Hire date", "Salary", "Status"], fields: [
    ["department", "Department", "department", true], ["user", "Linked user (optional)", "user"], ["first_name", "First name", "text", true], ["last_name", "Last name", "text", true], ["father_name", "Father name"], ["job_title", "Job title", "text", true], ["phone", "Phone"], ["email", "Email", "email"], ["address", "Address", "textarea"], ["national_id", "National ID"], ["hire_date", "Hire date", "date", true], ["end_date", "End date", "date"], ["salary", "Salary (AFN)", "number", true], ["status", "Status", "select", true, statusOptions],
  ]},
  attendance: { title: "Attendance", endpoint: "attendance", icon: UserRoundCheck, search: "employee number or name", columns: ["Employee", "Date", "Status", "Check in", "Check out", "Worked"], fields: [
    ["employee", "Employee", "employee", true], ["date", "Date", "date", true], ["status", "Status", "select", true, [["present", "Present"], ["absent", "Absent"], ["leave", "Leave"], ["half_day", "Half day"]]], ["check_in", "Check in", "time"], ["check_out", "Check out", "time"], ["check_out_date", "Check-out date (overnight)", "date"], ["notes", "Notes"],
  ]},
  payroll: { title: "Payroll", endpoint: "payroll", icon: WalletCards, search: "employee number or name", columns: ["Employee", "Period", "Base salary", "Allowances", "Deductions", "Net pay", "Status"], fields: [
    ["employee", "Employee", "employee", true], ["base_salary", "Base salary", "number", true], ["period_start", "Period start", "date", true], ["period_end", "Period end", "date", true], ["allowances", "Allowances", "number", true], ["deductions", "Deductions", "number", true], ["status", "Status", "select", true, [["draft", "Draft"], ["approved", "Approved"], ["paid", "Paid"], ["cancelled", "Cancelled"]]], ["notes", "Notes", "textarea"],
  ]},
  "payroll-components": { title: "Payroll components", endpoint: "payroll-components", icon: Banknote, columns: ["Payroll / employee", "Kind", "Description", "Amount", "Updated"], fields: [
    ["payroll", "Payroll record", "payroll", true], ["kind", "Kind", "select", true, [["allowance", "Allowance"], ["bonus", "Bonus"], ["overtime", "Overtime"], ["tax", "Tax"], ["advance", "Advance repayment"], ["deduction", "Other deduction"]]], ["description", "Description", "text", true], ["amount", "Amount", "number", true],
  ]},
  "leave-requests": { title: "Leave requests", endpoint: "leave-requests", icon: CalendarDays, columns: ["Employee", "Type", "Dates", "Days", "Status", "Reviewed by"], filters: [["status", "Any status", [["pending", "Pending"], ["approved", "Approved"], ["rejected", "Rejected"], ["cancelled", "Cancelled"]]]], fields: [
    ["employee", "Employee", "employee", true], ["leave_type", "Leave type", "select", true, [["annual", "Annual"], ["sick", "Sick"], ["unpaid", "Unpaid"], ["maternity", "Maternity"], ["paternity", "Paternity"], ["other", "Other"]]], ["start_date", "Start date", "date", true], ["end_date", "End date", "date", true], ["reason", "Reason", "textarea"], ["status", "Status", "select", true, [["pending", "Pending"], ["approved", "Approved"], ["rejected", "Rejected"], ["cancelled", "Cancelled"]]], ["review_notes", "Review notes", "textarea"],
  ]},
  "work-shifts": { title: "Work shifts", endpoint: "work-shifts", icon: Clock3, search: "shift name", columns: ["Shift", "Hours", "Break", "Working days", "Duration", "Status"], fields: [
    ["name", "Shift name", "text", true], ["start_time", "Start time", "time", true], ["end_time", "End time", "time", true], ["break_minutes", "Break (minutes)", "number", true], ["working_days", "Working days", "days", true], ["is_active", "Active", "boolean"],
  ]},
  "shift-assignments": { title: "Shift assignments", endpoint: "shift-assignments", icon: Clock3, columns: ["Employee", "Shift", "Start date", "End date", "Updated"], fields: [
    ["employee", "Employee", "employee", true], ["shift", "Work shift", "shift", true], ["start_date", "Start date", "date", true], ["end_date", "End date", "date"],
  ]},
  holidays: { title: "Holidays", endpoint: "holidays", icon: CalendarDays, columns: ["Holiday", "Date", "Department", "Paid", "Updated"], fields: [
    ["name", "Holiday name", "text", true], ["date", "Date", "date", true], ["department", "Department (blank means hospital-wide)", "department"], ["is_paid", "Paid holiday", "boolean"],
  ]},
  "salary-history": { title: "Salary history", endpoint: "salary-history", icon: History, columns: ["Employee", "Amount", "Effective from", "Reason", "Created"], fields: [
    ["employee", "Employee", "employee", true], ["amount", "Salary amount", "number", true], ["effective_from", "Effective from", "date", true], ["reason", "Reason"],
  ]},
  "employment-documents": { title: "Employment documents", endpoint: "employment-documents", icon: FileText, columns: ["Employee", "Document", "Type", "Issued", "Expires", "File"], fields: [
    ["employee", "Employee", "employee", true], ["document_type", "Document type", "select", true, [["contract", "Contract"], ["identity", "Identity"], ["certificate", "Certificate"], ["license", "Professional license"], ["other", "Other"]]], ["title", "Title", "text", true], ["file", "File", "file", true], ["issued_on", "Issued on", "date"], ["expires_on", "Expires on", "date"],
  ]},
  "employment-assignments": { title: "Assignment history", endpoint: "employment-assignments", icon: History, columns: ["Employee", "Department", "Job title", "Start date", "End date", "Reason"], fields: [
    ["employee", "Employee", "employee", true], ["department", "Department", "department", true], ["job_title", "Job title", "text", true], ["start_date", "Start date", "date", true], ["end_date", "End date", "date"], ["reason", "Reason"],
  ]},
};
const tabOrder = ["overview", "employees", "attendance", "leave-requests", "payroll", "payroll-components", "work-shifts", "shift-assignments", "holidays", "salary-history", "employment-documents", "employment-assignments"];
const tones = { active: "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300", present: "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300", approved: "bg-blue-50 dark:bg-blue-950/40 text-blue-700 dark:text-blue-300", paid: "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300", pending: "bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-300", draft: "bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300", leave: "bg-violet-50 dark:bg-violet-950/40 text-violet-700 dark:text-violet-300", half_day: "bg-cyan-50 dark:bg-cyan-950/40 text-cyan-700 dark:text-cyan-300", rejected: "bg-red-50 dark:bg-red-950/40 text-red-700 dark:text-red-300", cancelled: "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300", terminated: "bg-red-50 dark:bg-red-950/40 text-red-700 dark:text-red-300", suspended: "bg-orange-50 dark:bg-orange-950/40 text-orange-700 dark:text-orange-300", absent: "bg-red-50 dark:bg-red-950/40 text-red-700 dark:text-red-300" };
const nullableEmptyFields = new Set(["user", "employee", "department", "shift", "payroll", "hire_date", "end_date", "date", "check_in", "check_out", "check_out_date", "period_start", "period_end", "start_date", "issued_on", "expires_on", "effective_from", "national_id"]);

export default function HRPage() {
  const { user: account } = useAuth(); const user = withSectionRole(account, "hr"); const [tab, setTab] = useState("overview"); const [notice, setNotice] = useState("");
  if (!hasRole(user, ...HR_ROLES)) return <Alert variant="destructive"><AlertCircle /><AlertDescription>You do not have access to human resources.</AlertDescription></Alert>;
  return <div className="pharmacy-section">
    <div className="mb-7 rounded-2xl border border-cyan-100 dark:border-cyan-800 bg-gradient-to-br from-white dark:from-slate-900 via-white dark:via-slate-900 to-cyan-50/70 dark:to-cyan-950/40 px-5 py-6 shadow-sm sm:px-7"><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-cyan-700 dark:text-cyan-300">People and workforce operations</p><h1 className="text-3xl font-semibold tracking-[-.035em] text-slate-950 dark:text-slate-50 sm:text-4xl">Human resources</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">Employees, attendance, leave, payroll, shifts, documents, and employment history in one workspace.</p></div>
    {notice && <Alert className="mb-4 border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/40"><AlertDescription className="text-emerald-800 dark:text-emerald-300">{notice}</AlertDescription></Alert>}
    <div className="tab-scrollbar mb-7 flex gap-2 overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-1.5 pb-2 shadow-sm" role="tablist">
      {tabOrder.map((key) => { const cfg = configs[key]; const Icon = key === "overview" ? UsersRound : cfg.icon; return <Button key={key} role="tab" variant={tab === key ? "default" : "outline"} className={tab === key ? "border-cyan-700 bg-cyan-700 hover:bg-cyan-800" : "border-transparent bg-transparent text-slate-600 dark:text-slate-300 shadow-none"} onClick={() => setTab(key)}><Icon />{key === "overview" ? "Overview" : cfg.title}</Button>; })}
    </div>
    {tab === "overview" ? <Overview go={setTab} /> : <ResourcePage kind={tab} user={user} notify={setNotice} />}
  </div>;
}

function Overview({ go }) {
  const { t } = useLanguage();
  const [data, setData] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all([hrApi("employees/?page_size=200"), hrApi(`attendance/?date=${today()}&page_size=200`), hrApi("leave-requests/?status=pending&page_size=200"), hrApi("payroll/?status=draft&page_size=200")]).then(([e, a, l, p]) => setData({ employees: rows(e), attendance: rows(a), leaves: rows(l), payroll: rows(p) })).catch((x) => setError(x.message)).finally(() => setLoading(false)); }, []);
  const employees = data.employees || []; const attendance = data.attendance || []; const leaves = data.leaves || []; const payroll = data.payroll || [];
  const active = employees.filter((x) => x.status === "active").length; const present = attendance.filter((x) => x.status === "present").length; const attendanceRate = active ? Math.round((present / active) * 100) : 0; const draftTotal = payroll.reduce((sum, x) => sum + Number(x.net_pay || 0), 0);
  const attendanceGroups = [["Present", "present", "bg-emerald-500"], ["Half day", "half_day", "bg-cyan-500"], ["On leave", "leave", "bg-violet-500"], ["Absent", "absent", "bg-red-400"]];
  const cards = [["Active employees", active, t(`${employees.length} total employees`), UsersRound, "text-cyan-700 dark:text-cyan-300 bg-cyan-50 dark:bg-cyan-950/40"], ["Present today", present, t(`${attendanceRate}% of active workforce`), UserRoundCheck, "text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/40"], ["Pending leave", leaves.length, leaves.length ? "Awaiting HR review" : "All requests reviewed", CalendarDays, "text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-950/40"], ["Draft payroll", payroll.length, t(`AFN ${money(draftTotal)} net total`), WalletCards, "text-violet-700 dark:text-violet-300 bg-violet-50 dark:bg-violet-950/40"]];
  return <div>{error && <ErrorBox message={error} />}
    <div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-slate-50">Workforce overview</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Today&apos;s people operations at a glance · {formatDate(today())}</p></div><Button variant="outline" className="self-start sm:self-auto" onClick={() => go("employees")}>View employee directory <ArrowUpRight /></Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, caption, Icon, tone]) => <Card key={label} className="relative overflow-hidden p-5 shadow-sm transition-shadow hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-slate-50">{loading ? "…" : value}</p></div><span className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${tone}`}><Icon className="size-5" /></span></div><p className="mt-3 border-t border-slate-100 dark:border-slate-800 pt-3 text-xs text-slate-500 dark:text-slate-400">{loading ? "Loading workforce data…" : caption}</p></Card>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <Card className="gap-0 overflow-hidden py-0 shadow-sm"><OverviewHeader title="Today’s attendance" subtitle={`${attendance.length} attendance records captured`} action="Open attendance" onClick={() => go("attendance")} /><div className="p-5"><div className="mb-5 flex items-end justify-between rounded-xl bg-gradient-to-br from-cyan-700 to-cyan-900 p-5 text-white"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-100">Attendance rate</p><p className="mt-2 text-4xl font-semibold tracking-tight">{loading ? "—" : `${attendanceRate}%`}</p><p className="mt-1 text-xs text-cyan-100">{present} of {active} active employees present</p></div><UserRoundCheck className="size-12 text-white/20" /></div><div className="space-y-4">{attendanceGroups.map(([label, status, color]) => { const count = attendance.filter((x) => x.status === status).length; const percent = attendance.length ? Math.round((count / attendance.length) * 100) : 0; return <div key={status}><div className="mb-1.5 flex justify-between text-sm"><span className="font-medium text-slate-700 dark:text-slate-300">{label}</span><span className="tabular-nums text-slate-500 dark:text-slate-400">{count} · {percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{ width: `${percent}%` }} /></div></div>; })}</div></div></Card>
      <Card className="gap-0 overflow-hidden py-0 shadow-sm"><OverviewHeader title="Leave requiring attention" subtitle="Pending requests, earliest start first" action="Review all" onClick={() => go("leave-requests")} /><div className="divide-y divide-slate-100 dark:divide-slate-800">{loading ? <div className="py-14 text-center text-sm text-slate-500 dark:text-slate-400"><LoaderCircle className="mx-auto mb-2 animate-spin" />Loading requests…</div> : !leaves.length ? <div className="px-5 py-14 text-center"><span className="mx-auto flex size-11 items-center justify-center rounded-full bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-300"><UserRoundCheck /></span><p className="mt-3 font-medium text-slate-800 dark:text-slate-200">Everything is up to date</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">There are no pending leave requests.</p></div> : leaves.slice(0, 5).map((leave) => <button key={leave.id} type="button" onClick={() => go("leave-requests")} className="flex w-full items-center gap-3 px-5 py-4 text-left transition hover:bg-cyan-50/50"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-amber-50 dark:bg-amber-950/40 text-xs font-bold text-amber-700 dark:text-amber-300">{leave.employee_name?.split(" ").map((x) => x[0]).slice(0, 2).join("") || "E"}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-900 dark:text-slate-100">{leave.employee_name}</strong><small className="block truncate text-slate-500 dark:text-slate-400">{labelize(leave.leave_type)} · {formatDate(leave.start_date)}–{formatDate(leave.end_date)}</small></span><Badge variant="secondary" className="bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-300">{leave.total_days}d</Badge></button>)}</div></Card>
    </div>
    <Card className="mt-5 gap-0 overflow-hidden py-0 shadow-sm"><div className="border-b bg-slate-50/60 dark:bg-slate-900/60 px-5 py-4"><h3 className="font-semibold text-slate-900 dark:text-slate-100">Quick actions</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">Jump directly to common HR workflows</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{[["employees", "Manage employees", "Profiles and employment details", UsersRound], ["attendance", "Record attendance", "Daily check-in and status", UserRoundCheck], ["leave-requests", "Review leave", "Approve pending requests", CalendarDays], ["payroll", "Process payroll", "Draft and approve payroll", WalletCards]].map(([key, label, caption, Icon], index) => <button key={key} type="button" onClick={() => go(key)} className={`group flex items-center gap-3 p-5 text-left transition hover:bg-cyan-50/60 ${index ? "border-t sm:border-l sm:border-t-0" : ""}`}><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 transition group-hover:bg-cyan-100 group-hover:text-cyan-700"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-900 dark:text-slate-100">{label}</strong><small className="mt-0.5 block text-slate-500 dark:text-slate-400">{caption}</small></span><ArrowUpRight className="size-4 text-slate-300 transition group-hover:text-cyan-600" /></button>)}</div></Card>
  </div>;
}

function OverviewHeader({ title, subtitle, action, onClick }) { return <div className="flex items-center justify-between gap-3 border-b bg-slate-50/60 dark:bg-slate-900/60 px-5 py-4"><div><h3 className="font-semibold text-slate-900 dark:text-slate-100">{title}</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{subtitle}</p></div><Button size="sm" variant="ghost" className="text-cyan-700 dark:text-cyan-300" onClick={onClick}>{action}<ArrowUpRight /></Button></div>; }

function ResourcePage({ kind, user, notify }) {
  const { t } = useLanguage();
  const cfg = configs[kind]; const [query, setQuery] = useState(""); const [filters, setFilters] = useState({}); const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(null); const [selected, setSelected] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); const params = new URLSearchParams({ page: String(page) }); if (query.trim() && cfg.search) params.set("search", query.trim()); Object.entries(filters).forEach(([k, v]) => v && params.set(k, v)); try { setData(await hrApi(`${cfg.endpoint}/?${params}`)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [cfg, filters, page, query]);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load, refresh]); const items = rows(data); const write = hasRole(user, ...HR_WRITE_ROLES);
  const saved = (message) => { setModal(null); setSelected(null); notify(message); setRefresh((x) => x + 1); };
  return <div><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight">{cfg.title}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{t(`${data?.count ?? items.length} records`)}</p></div>{write && <Button className="bg-cyan-700 hover:bg-cyan-800" onClick={() => { setSelected(null); setModal("form"); }}><Plus />New record</Button>}</div>{error && <ErrorBox message={error} retry={() => setRefresh((x) => x + 1)} />}
    <Card className="gap-0 overflow-hidden py-0"><div className="flex flex-wrap gap-3 border-b bg-slate-50/60 dark:bg-slate-900/60 p-4">{cfg.search && <div className="relative min-w-60 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400 dark:text-slate-500" /><Input className="pl-9" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder={`Search by ${cfg.search}…`} /></div>}{cfg.filters?.map(([name, placeholder, options]) => <div className="min-w-44" key={name}><Select value={filters[name] || ""} placeholder={placeholder} options={options} onChange={(v) => { setFilters({ ...filters, [name]: v }); setPage(1); }} /></div>)}<Button variant="outline" size="icon" onClick={() => setRefresh((x) => x + 1)} aria-label="Refresh"><RefreshCw className={loading ? "animate-spin" : ""} /></Button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-900/60 text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400"><tr>{cfg.columns.map((c) => <th key={c} className="px-5 py-3.5">{c}</th>)}<th className="px-5 py-3.5"><span className="sr-only">Actions</span></th></tr></thead><tbody>{loading ? <tr><td colSpan={cfg.columns.length + 1} className="py-16 text-center text-slate-500 dark:text-slate-400"><LoaderCircle className="mx-auto mb-2 animate-spin" />Loading…</td></tr> : !items.length ? <tr><td colSpan={cfg.columns.length + 1} className="py-16 text-center text-slate-500 dark:text-slate-400">No records found.</td></tr> : items.map((item) => <RecordRow key={item.id} kind={kind} item={item} write={write} edit={() => { setSelected(item); setModal("form"); }} detail={() => { setSelected(item); setModal("detail"); }} remove={() => { setSelected(item); setModal("delete"); }} />)}</tbody></table></div>
      <div className="flex items-center justify-between border-t bg-slate-50/50 dark:bg-slate-900/50 px-5 py-4"><span className="text-sm text-slate-500 dark:text-slate-400">{t(`${data?.count ?? items.length} total`)}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={!data?.previous || loading} onClick={() => setPage((p) => p - 1)}>Previous</Button><span className="px-2 text-xs text-slate-500 dark:text-slate-400">{t(`Page ${page}`)}</span><Button size="sm" variant="outline" disabled={!data?.next || loading} onClick={() => setPage((p) => p + 1)}>Next</Button></div></div>
    </Card>
    {modal === "form" && <RecordForm kind={kind} item={selected} onClose={() => setModal(null)} onSaved={() => saved(`${cfg.title} record ${selected ? "updated" : "created"}.`)} />}{modal === "detail" && <Detail kind={kind} item={selected} write={write} onClose={() => setModal(null)} onEdit={() => setModal("form")} />}{modal === "delete" && <DeleteRecord cfg={cfg} item={selected} onClose={() => setModal(null)} onSaved={() => saved("Record deleted.")} />}
  </div>;
}

function RecordRow({ kind, item, write, edit, detail, remove }) {
  const label = item.full_name || item.employee_name || item.name || item.title || "record";

  return (
    <tr className="border-t hover:bg-cyan-50/40">
      {cells(kind, item).map((value, i) => (
        <td key={i} className="px-5 py-4">{value}</td>
      ))}
      <td className="px-5 py-4 text-right">
        <DropdownMenu>
          <DropdownMenuTrigger
            render={
              <Button
                variant="ghost"
                size="icon-sm"
                aria-label={`Actions for ${label}`}
                title="Actions"
                className="rounded-md text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-900 data-[state=open]:bg-slate-100 dark:data-[state=open]:bg-slate-800 data-[state=open]:text-slate-900"
              />
            }
          >
            <MoreHorizontal className="size-4" />
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-40 p-1.5">
            <DropdownMenuItem onClick={detail}>View</DropdownMenuItem>
            {write && (
              <>
                <DropdownMenuItem onClick={edit}>Edit</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem variant="destructive" onClick={remove}>
                  <Trash2 className="size-4" /> Delete
                </DropdownMenuItem>
              </>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </td>
    </tr>
  );
}
function Status({ value }) { return <Badge variant="secondary" className={tones[value] || "bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300"}>{labelize(value)}</Badge>; }
function cells(kind, x) {
  const person = <span><strong className="block">{x.employee_name || x.full_name}</strong><small className="text-slate-500 dark:text-slate-400">{x.employee_number}</small></span>;
  const date = (v) => formatDate(v); const cash = (v) => `AFN ${money(v)}`;
  return ({ employees: [person, x.department_name, x.job_title, date(x.hire_date), cash(x.salary), <Status key="s" value={x.status} />], attendance: [person, date(x.date), <Status key="s" value={x.status} />, x.check_in || "—", x.check_out ? `${x.check_out}${x.check_out_date && x.check_out_date !== x.date ? ` · ${date(x.check_out_date)}` : ""}` : "—", x.worked_duration || "—"], payroll: [person, `${date(x.period_start)} – ${date(x.period_end)}`, cash(x.base_salary), cash(x.allowances), cash(x.deductions), <strong key="n">{cash(x.net_pay)}</strong>, <Status key="s" value={x.status} />], "payroll-components": [x.payroll, labelize(x.kind), x.description, cash(x.amount), date(x.updated_at)], "leave-requests": [person, labelize(x.leave_type), `${date(x.start_date)} – ${date(x.end_date)}`, x.total_days, <Status key="s" value={x.status} />, x.reviewed_by_name || "—"], "work-shifts": [<strong key="n">{x.name}</strong>, `${x.start_time} – ${x.end_time}`, `${x.break_minutes} min`, (x.working_days || []).map((d) => ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][d]).join(", "), x.scheduled_duration, <Status key="s" value={x.is_active ? "active" : "inactive"} />], "shift-assignments": [person, x.shift_name, date(x.start_date), date(x.end_date), date(x.updated_at)], holidays: [<strong key="n">{x.name}</strong>, date(x.date), x.department_name || "Hospital-wide", x.is_paid ? "Yes" : "No", date(x.updated_at)], "salary-history": [person, cash(x.amount), date(x.effective_from), x.reason || "—", date(x.created_at)], "employment-documents": [person, x.title, labelize(x.document_type), date(x.issued_on), date(x.expires_on), x.file ? <a key="f" className="text-cyan-700 dark:text-cyan-300 underline" href={x.file} target="_blank" rel="noreferrer">Open</a> : "—"], "employment-assignments": [person, x.department_name, x.job_title, date(x.start_date), date(x.end_date), x.reason || "—"] })[kind];
}

function RecordForm({ kind, item, onClose, onSaved }) {
  const { t } = useLanguage();
  const cfg = configs[kind]; const initial = Object.fromEntries(cfg.fields.map(([name, , type]) => [name, item?.[name] ?? (type === "boolean" ? true : type === "days" ? [0, 1, 2, 3, 4] : "")]));
  const errorRef = useRef(null);
  const [form, setForm] = useState(initial); const [lookups, setLookups] = useState({ employees: [], departments: [], users: [], shifts: [], payroll: [] }); const [error, setError] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; const types = new Set(cfg.fields.map((x) => x[2])); const requests = [["employee", "employees", "employees/?page_size=500&ordering=first_name"], ["department", "departments", "departments/?page_size=500&ordering=name"], ["user", "users", "users/?page_size=500&ordering=first_name"], ["shift", "shifts", "work-shifts/?page_size=500&ordering=name"], ["payroll", "payroll", "payroll/?page_size=500&ordering=-period_end"]].filter(([type]) => types.has(type)); Promise.allSettled(requests.map(([, , path]) => hrApi(path))).then((results) => { if (!active) return; const loaded = {}; let lookupError = null; results.forEach((result, i) => { const [type, key] = requests[i]; if (result.status === "fulfilled") loaded[key] = rows(result.value); else if (cfg.fields.some(([name, , fieldType, required]) => fieldType === type && required)) lookupError = result.reason; }); setLookups((old) => ({ ...old, ...loaded })); if (lookupError) setError(lookupError); }); return () => { active = false; }; }, [cfg]);
  useEffect(() => { if (error) errorRef.current?.scrollIntoView({ block: "center", behavior: "smooth" }); }, [error]);
  useEffect(() => {
    if (kind !== "payroll" || !form.employee) return;
    const selectedEmployee = (lookups.employees || []).find((employee) => employee.id === form.employee);
    if (!selectedEmployee || selectedEmployee.salary == null) return;
    const salaryValue = Number(selectedEmployee.salary);
    setForm((current) => (current.base_salary === salaryValue ? current : { ...current, base_salary: salaryValue }));
  }, [kind, form.employee, lookups.employees]);
  function invalid(e) { e.preventDefault(); e.target.scrollIntoView({ block: "center", behavior: "smooth" }); e.target.focus(); const validationError = new Error(t("Please complete the required fields.")); validationError.fields = { [e.target.name || "field"]: validationError.message }; setError(validationError); }
  async function submit(e) { e.preventDefault(); setSaving(true); setError(null); try { let body; const options = { method: item ? "PATCH" : "POST" }; if (kind === "employment-documents" && form.file instanceof File) { body = new FormData(); Object.entries(form).forEach(([k, v]) => { if (v !== "" && v != null) body.append(k, v); }); } else { const payload = { ...form }; Object.keys(payload).forEach((k) => payload[k] === "" && nullableEmptyFields.has(k) && (payload[k] = null)); body = JSON.stringify(payload); options.headers = { "Content-Type": "application/json" }; } options.body = body; await hrApi(`${cfg.endpoint}/${item ? `${item.id}/` : ""}`, options); onSaved(); } catch (x) { setError(x); } finally { setSaving(false); } }
  return <Modal title={`${item ? "Edit" : "New"} ${cfg.title.toLowerCase()} record`} subtitle="Required fields are marked with an asterisk." onClose={onClose} wide><form onSubmit={submit} onInvalid={invalid} className="space-y-6">{error && <div ref={errorRef}><FormError error={error} /></div>}<div className="grid gap-4 sm:grid-cols-2">{cfg.fields.map((field) => <DynamicField key={field[0]} field={field} value={form[field[0]]} item={item} kind={kind} lookups={lookups} error={inputError(error, field[0])} set={(value) => setForm({ ...form, [field[0]]: value })} />)}</div><div className="flex justify-end gap-3 border-t border-slate-200/80 pt-5"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving} className="bg-cyan-700 text-white hover:bg-cyan-800">{saving && <LoaderCircle className="animate-spin" />}Save record</Button></div></form></Modal>;
}

function DynamicField({ field, value, item, kind, lookups, error, set }) { const [name, label, type = "text", required, options] = field; if (type === "boolean") return <label className="flex items-center gap-3 rounded-xl border p-4 sm:self-end"><Checkbox checked={Boolean(value)} onCheckedChange={(v) => set(Boolean(v))} /><span className="text-sm font-semibold">{label}</span></label>; if (type === "days") return <div className="space-y-2 sm:col-span-2"><p className="text-sm font-semibold text-slate-700 dark:text-slate-300">{label} *</p><div className="flex flex-wrap gap-2">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <label key={day} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Checkbox checked={value.includes(index)} onCheckedChange={(checked) => set(checked ? [...value, index].sort() : value.filter((x) => x !== index))} />{day}</label>)}</div>{error && <p className="text-xs text-red-600 dark:text-red-300">{error}</p>}</div>;
  let control; const common = { name, required, value: value ?? "", onChange: (e) => set(e.target.value) };
  if (type === "textarea") control = <Textarea {...common} />; else if (type === "date") control = <DatePicker name={name} required={required} value={value ?? ""} onChange={set} />; else if (type === "select") control = <Select required={required} value={value ?? ""} onChange={set} options={options} />; else if (["employee", "department", "user", "shift", "payroll"].includes(type)) { const list = lookups[{ employee: "employees", department: "departments", user: "users", shift: "shifts", payroll: "payroll" }[type]] || []; const labels = { employee: (x) => `${x.full_name} · ${x.employee_number}`, department: (x) => x.name, user: (x) => `${x.first_name || ""} ${x.last_name || ""}`.trim() || x.username, shift: (x) => x.name, payroll: (x) => `${x.employee_name} · ${formatDate(x.period_start)}–${formatDate(x.period_end)} · ${labelize(x.status)}` }; 
    if (list.length === 0) {
      control = <Select required={required} value={value ?? ""} onChange={set} options={[]} placeholder="Loading..." disabled />;
    } else {
      control = <Select required={required} value={value ?? ""} onChange={set} options={list.map((x) => [x.id, labels[type](x)])} placeholder={`Select ${label.toLowerCase()}`} />;
    }
  } else if (type === "file") control = <Input required={required && !item} type="file" onChange={(e) => set(e.target.files?.[0] || "")} />; else if (kind === "payroll" && name === "base_salary") control = <Input {...common} type={type} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} readOnly disabled />; else control = <Input {...common} type={type} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} />;
  return <div className={type === "textarea" || name === "address" ? "sm:col-span-2" : ""}><Field label={label} error={error}>{control}</Field></div>;
}

function Detail({ kind, item, write, onClose, onEdit }) { const excluded = new Set(["id", "created_at", "updated_at", "file", "components"]); return <Modal title={item.full_name || item.employee_name || item.name || item.title || configs[kind].title} subtitle={configs[kind].title} onClose={onClose} wide><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(item).filter(([k, v]) => !excluded.has(k) && v !== null && v !== "" && typeof v !== "object").map(([key, value]) => <div key={key} className="rounded-2xl border border-slate-200/80 bg-white/80 p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900/60"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">{labelize(key)}</p><p className="mt-2 break-words text-sm font-semibold text-slate-800 dark:text-slate-100">{formatValue(key, value)}</p></div>)}</div>{item.components?.length > 0 && <div className="mt-5 rounded-2xl border border-slate-200/80 bg-white/80 p-4 dark:border-slate-700 dark:bg-slate-900/60"><h3 className="mb-3 text-sm font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">Payroll components</h3>{item.components.map((c) => <div key={c.id} className="flex items-center justify-between gap-3 border-b border-slate-200/80 py-2.5 text-sm last:border-b-0 dark:border-slate-700"><span className="text-slate-700 dark:text-slate-200">{labelize(c.kind)} · {c.description}</span><strong className="text-slate-900 dark:text-slate-100">AFN {money(c.amount)}</strong></div>)}</div>}<div className="mt-6 flex justify-end gap-3 border-t border-slate-200/80 pt-5"><Button variant="outline" onClick={onClose}>Close</Button>{write && <Button onClick={onEdit} className="bg-cyan-700 text-white hover:bg-cyan-800">Edit</Button>}</div></Modal>; }
function formatValue(key, value) { if (typeof value === "boolean") return value ? "Yes" : "No"; if (key.includes("salary") || ["amount", "allowances", "deductions", "gross_pay", "net_pay"].includes(key)) return `AFN ${money(value)}`; if (key.endsWith("_at")) return formatDate(value, true); if (key.endsWith("_date") || key.endsWith("_on") || key.startsWith("period_") || key === "effective_from") return formatDate(value); return labelize(value); }
function DeleteRecord({ cfg, item, onClose, onSaved }) { const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function remove() { setSaving(true); setError(""); try { await hrApi(`${cfg.endpoint}/${item.id}/`, { method: "DELETE" }); onSaved(); } catch (e) { setError(e.message); setSaving(false); } } return <Modal title="Delete record" subtitle="This action is permanent and may be blocked when the record is in use." onClose={onClose}><div className="rounded-2xl border border-red-200 bg-red-50/80 p-4 dark:border-red-900/60 dark:bg-red-950/30">{error && <ErrorBox message={error} />}<p className="text-sm text-slate-700 dark:text-slate-200">Delete this {cfg.title.toLowerCase()} record?</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">This action cannot be undone.</p></div><div className="mt-6 flex justify-end gap-3 border-t border-slate-200/80 pt-5"><Button variant="outline" onClick={onClose}>Cancel</Button><Button variant="destructive" disabled={saving} onClick={remove}>{saving ? <LoaderCircle className="animate-spin" /> : <Trash2 />}Delete</Button></div></Modal>; }
function ErrorBox({ message, retry }) { return <Alert variant="destructive" className="mb-4"><AlertCircle /><AlertDescription className="flex items-center justify-between gap-3">{message}{retry && <Button size="sm" variant="outline" onClick={retry}>Retry</Button>}</AlertDescription></Alert>; }
function FormError({ error }) { const messages = readableErrors(error?.fields, error?.status); return <Alert variant="destructive"><AlertCircle /><AlertDescription><strong>We couldn&apos;t save this information.</strong><ul className="mt-1 list-disc pl-5">{(messages.length ? messages : [error.message]).map((m, i) => <li key={i}>{m}</li>)}</ul></AlertDescription></Alert>; }
